//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sumOfDigits", ReplyAction="http://tempuri.org/IService1/sumOfDigitsResponse")]
        int sumOfDigits(int digits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sumOfDigits", ReplyAction="http://tempuri.org/IService1/sumOfDigitsResponse")]
        System.Threading.Tasks.Task<int> sumOfDigitsAsync(int digits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numOfVowels", ReplyAction="http://tempuri.org/IService1/numOfVowelsResponse")]
        int numOfVowels(string possibleVowelString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numOfVowels", ReplyAction="http://tempuri.org/IService1/numOfVowelsResponse")]
        System.Threading.Tasks.Task<int> numOfVowelsAsync(string possibleVowelString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SoapClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SoapClient.ServiceReference1.IService1>, SoapClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sumOfDigits(int digits) {
            return base.Channel.sumOfDigits(digits);
        }
        
        public System.Threading.Tasks.Task<int> sumOfDigitsAsync(int digits) {
            return base.Channel.sumOfDigitsAsync(digits);
        }
        
        public int numOfVowels(string possibleVowelString) {
            return base.Channel.numOfVowels(possibleVowelString);
        }
        
        public System.Threading.Tasks.Task<int> numOfVowelsAsync(string possibleVowelString) {
            return base.Channel.numOfVowelsAsync(possibleVowelString);
        }
    }
}
